server:
  port: 8999

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: mpw:8GKl0pODM2gGQK2Mom41SUfnBAB+q0vdzWEKSN3FpzhujcwqUTdNfKuzWAe58H6Pvp3TNKicwQzbflv/gBx3s4hau0442xczBYcOo3xwNQiLX8s1CbapVs2PyfviQBSy2iFlSIVVWciu41I/q0kyJoQXwywGT7HNXJOfMtOEOgu4K5bKieCDrMhdQCsZPqHO
    username: mpw:tuI9qo5UWVRSmcNfb7N5xg==
    password: mpw:0jfWe1ZtwCNcOmD4pj94Kg==

study:
  db-type: mysql
  email:
    form: 15093959810@163.com  # 发件人邮箱
    password: LKbZgmuJ4nE9pxMs  # 163邮箱的授权码（不是登录密码）
    host: smtp.163.com       # SMTP服务器地址
    protocol: smtp           # 协议
  skip-validation:
    - /auth/authenticate

# 配置 Mybatis-Plus 的全局配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 数据库配置
    db-config:
      # 逻辑删除字段名
      logic-delete-field: deleted
      # 逻辑删除值
      logic-delete-value: 1
      # 非逻辑删除值
      logic-not-delete-value: 0

