spring:
  application:
    name: ai_code_test

langchain4j:
  open-ai:
    chat-model:
      api-key: sk-660e9de114e841a2aa7bfbacd8aa890e
      base-url: https://api.deepseek.com
      model-name: deepseek-chat
      max-tokens: 4096